import './globals.css';
import Navigation from './components/navigation';
import Footer from './components/footer';
import { MainContent } from './components/mainContent';

export const metadata = {
  title: 'DXPosed',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <MainContent>{children}</MainContent>
        {/* <main className={`${isHome ? "" : "pt-20"} flex-grow`}>{children}</main> */}
        <Navigation />
        <Footer />
      </body>
    </html>
  );
}
