import './globals.css';
import Navigation from './components/navigation';
import { Inter } from 'next/font/google';
import Footer from './components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'DXPosed',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='flex flex-col min-h-screen'>
          <Navigation />
          <main className='flex-grow'>
            <div className='container mx-auto py-8'>{children}</div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
